const $=s=>document.querySelector(s); const Q=window.COMPASS_QUESTIONS||[];
const key='inspectorsCompass.v1';
let state=JSON.parse(localStorage.getItem(key)||'null')||{answered:0,correct:0,bookmarks:[],seen:{},streak:0,lastDay:null};
let session={mode:'home',list:[],i:0,selected:null,revealed:false};
function save(){localStorage.setItem(key,JSON.stringify(state))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(content,tab='home'){return `<header><div class="brand"><div class="badge">IC</div><div><b>Inspector's Compass</b><small>34-day revision mode</small></div></div><button class="ghost" onclick="resetProgress()" aria-label="Reset progress">↻</button></header><main>${content}</main><nav>${[['home','⌂','Home'],['learn','▤','Learn'],['quiz','✓','Quiz'],['saved','★','Saved']].map(([id,ic,l])=>`<button class="${tab===id?'active':''}" onclick="go('${id}')"><span>${ic}</span>${l}</button>`).join('')}</nav>`}
function home(){const pct=state.answered?Math.round(state.correct/state.answered*100):0; const topics=[...new Set(Q.map(q=>q.topic))]; return shell(`<section class="hero"><p class="eyebrow">INSPECTOR EXAM</p><h1>Know it. Retrieve it.<br>Use it under pressure.</h1><p>Short, repeatable sessions built around active recall.</p><button class="primary" onclick="startQuiz()">Start 5-question drill →</button></section><section class="stats"><div><strong>${state.answered}</strong><span>Answered</span></div><div><strong>${pct}%</strong><span>Accuracy</span></div><div><strong>${state.bookmarks.length}</strong><span>Saved</span></div></section><h2>Revision areas</h2>${topics.map(t=>`<button class="topic" onclick="startTopic('${esc(t)}')"><span><b>${esc(t)}</b><small>${Q.filter(q=>q.topic===t).length} questions loaded</small></span><b>›</b></button>`).join('')}<div class="notice"><b>Built to grow.</b><br>Your verified question bank can be dropped into <code>questions.js</code> without rebuilding the interface.</div>`,'home')}
function learn(){const topics=[...new Set(Q.map(q=>q.topic))]; return shell(`<h1 class="pageTitle">Learn</h1><p class="muted">Compact revision cards. Read once, then test yourself.</p>${topics.map(t=>`<article class="card"><p class="eyebrow">${esc(t)}</p><h3>Core retrieval prompts</h3><p>Work the questions for this topic, read every explanation, and save anything you miss. The saved deck becomes your weak-area revision list.</p><button class="secondary" onclick="startTopic('${esc(t)}')">Study ${esc(t)}</button></article>`).join('')}`,'learn')}
function startQuiz(list=Q){session={mode:'quiz',list:[...list].sort(()=>Math.random()-.5).slice(0,5),i:0,selected:null,revealed:false}; renderQuestion()}
function startTopic(t){startQuiz(Q.filter(q=>q.topic===t))}
function renderQuestion(){if(session.i>=session.list.length)return finish(); const q=session.list[session.i]; const saved=state.bookmarks.includes(q.id); $('#app').innerHTML=shell(`<div class="quizTop"><button class="back" onclick="go('home')">‹ Exit</button><span>${session.i+1} / ${session.list.length}</span><button class="star ${saved?'on':''}" onclick="bookmark(${q.id})">★</button></div><div class="progress"><i style="width:${(session.i/session.list.length)*100}%"></i></div><p class="eyebrow">${esc(q.topic)}</p><h2 class="question">${esc(q.question)}</h2><div class="answers">${q.options.map((o,i)=>`<button class="answer ${session.revealed?(i===q.answer?'correct':i===session.selected?'wrong':''):session.selected===i?'chosen':''}" onclick="choose(${i})" ${session.revealed?'disabled':''}><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div>${session.revealed?`<article class="explain"><b>${session.selected===q.answer?'Correct':'Not quite'}</b><p>${esc(q.explanation)}</p><small>Reference: ${esc(q.reference)}</small></article><button class="primary" onclick="nextQ()">${session.i===session.list.length-1?'Finish':'Next question'} →</button>`:`<button class="primary" ${session.selected===null?'disabled':''} onclick="check()">Check answer</button>`}`,'quiz')}
function choose(i){session.selected=i;renderQuestion()}
function check(){if(session.selected===null)return; const q=session.list[session.i]; session.revealed=true; state.answered++; if(session.selected===q.answer)state.correct++; state.seen[q.id]=(state.seen[q.id]||0)+1; save();renderQuestion()}
function nextQ(){session.i++;session.selected=null;session.revealed=false;renderQuestion()}
function finish(){const total=session.list.length; $('#app').innerHTML=shell(`<section class="finish"><div class="bigcheck">✓</div><p class="eyebrow">DRILL COMPLETE</p><h1>Session finished.</h1><p>Your overall accuracy is ${state.answered?Math.round(state.correct/state.answered*100):0}%. Saved questions stay ready for another pass.</p><button class="primary" onclick="startQuiz()">Another 5</button><button class="secondary" onclick="go('saved')">Review saved</button></section>`,'quiz')}
function bookmark(id){state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];save();renderQuestion()}
function saved(){const qs=Q.filter(q=>state.bookmarks.includes(q.id)); const body=qs.length ? qs.map(q=>`<article class="card"><p class="eyebrow">${esc(q.topic)}</p><h3>${esc(q.question)}</h3><small>${esc(q.reference)}</small></article>`).join('')+`<button class="primary" onclick="startQuiz(Q.filter(q=>state.bookmarks.includes(q.id)))">Drill saved questions</button>` : `<div class="empty">★<h3>Nothing saved yet</h3><p>Tap the star during a quiz to build a targeted revision deck.</p></div>`; return shell(`<h1 class="pageTitle">Saved</h1><p class="muted">Your weak-area deck.</p>${body}`,'saved')}
function go(p){session.mode=p; $('#app').innerHTML=p==='home'?home():p==='learn'?learn():p==='saved'?saved():home(); window.scrollTo(0,0)}
function resetProgress(){if(confirm('Reset all Compass progress and bookmarks?')){localStorage.removeItem(key);location.reload()}}
$('#app').innerHTML=home(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
